runner:
  # "pylint errors":
  #   cmd: docker run --rm t0ster/authproxy:test pylint -E *.py
  #   errorformat:
  #     - "%f:%l:%c: %t%n: %m"
  #   level: error
  pylint:
    cmd: docker run --rm t0ster/authproxy:test pylint *.py
    errorformat:
      - "%f:%l:%c: %t%n: %m"
    level: info
